server:
  port: 8080
spring:
  application:
    name: weddy
  profiles:
    active: common, user
  config:
    import: optional:configserver:***REMOVED***:8888
  cloud:
    gateway:
      routes:
        # OAuth2 전용 라우트를 최상위로 배치
        - id: oauth2-route
          uri: http://user.default.svc.cluster.local:8080
          predicates:
            - Path=/api/oauth2/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            # JWT 필터가 있다면 OAuth2 라우트에서는 제외
            - name: Retry
              args:
                retries: 3
                methods: GET
                
        - id: product-service
          uri: http://product.default.svc.cluster.local:8080
          predicates:
            - Path=/api/products/**, /api/venders/**

        - id: schedule-service
          uri: http://schedule.default.svc.cluster.local:8080
          predicates:
            - Path=/api/schedules/**

        - id: user-service
          uri: http://user.default.svc.cluster.local:8080
          predicates:
            - Path=/api/users/**, /api/payments/**, /api/contracts/**, /api/login/**

      # 글로벌 CORS 설정 추가
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "https://weddy.info"
              - "http://localhost:3000"  # 개발 환경용
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

# server:
#   port: 8080
# spring:
#   application:
#     name: weddy
#   profiles:
#     active: common, user
#   config:
#     import: optional:configserver:***REMOVED***:8888
#   cloud:
#     gateway:
#       routes:
#         - id: product-service
#           uri: http://product.default.svc.cluster.local:8080  # 여기 수정
#           predicates:
#             - Path=/api/products/**, /api/venders/**

#         - id: schedule-service
#           uri: http://schedule.default.svc.cluster.local:8080  # 여기도 수정
#           predicates:
#             - Path=/api/schedules/**

#         - id: user-service
#           uri: http://user.default.svc.cluster.local:8080  # 여기도 수정
#           predicates:
#             - Path=/api/users/**, /api/payments/**, /api/contracts/**, /api/login/**, /api/oauth2/**


#        - id: order-service
#          uri: http://localhost:8082  # order-service? ??
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
