server:
  port: 8080
spring:
  application:
    name: weddy
  profiles:
    active: common, user
  config:
    import: optional:configserver:***REMOVED***:8888
  # 이 부분 weddy-user-deployment.yml로 config 폴더에 만들긴 했는데 바꾸고 싶으면 바뀌십쇼
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product:8080
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: schedule-service
          uri: http://schedule:8080
          predicates:
            - Path=/api/schedules/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: http://user:8080
          predicates:
            - Path=/api/users/**, /api/payments/**, /api/contracts/**, /api/login/**, /api/oauth2/**
          filters:
            - StripPrefix=1


#        - id: order-service
#          uri: http://localhost:8082  # order-service? ??
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
