server:
  port: 8080
spring:
  application:
    name: weddy
  profiles:
    active: common, user
  config:
    import: optional:configserver:***REMOVED***:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081  # user-service? ??
          predicates:
            - Path=/api/users, /api/users/**, /api/login, /api/login/**


#        - id: order-service
#          uri: http://localhost:8082  # order-service? ??
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1