spring:
  application:
    name: weddy
  profiles:
    active: common, product
  config:
    import: optional:configserver:***REMOVED***:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, prometheus


## 나중에 바꿔야함
server:
  port: 8080