spring:
  application:
    name: weddy
  profiles:
    active: common
  config:
    import: optional:configserver:***REMOVED***:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh